# Generated by Django 4.2.9 on 2024-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0002_installer_users_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='password',
            field=models.CharField(default='password123', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='janeDoe@greek.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='password123', max_length=100),
        ),
    ]
