# Generated by Django 4.2.9 on 2024-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0003_installer_password_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='email_address',
        ),
        migrations.AddField(
            model_name='installer',
            name='email',
            field=models.EmailField(default='janeDoe@greek.com', max_length=254),
        ),
    ]
