# Generated by Django 4.2.9 on 2024-02-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0004_remove_installer_email_address_installer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
