# Generated by Django 4.2.9 on 2024-02-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0005_rename_user_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installer',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='installer',
            name='first_name',
            field=models.CharField(default='Jane', max_length=302),
        ),
        migrations.AddField(
            model_name='installer',
            name='last_name',
            field=models.CharField(default='Doe', max_length=30),
        ),
    ]
