# Generated by Django 4.2.9 on 2024-02-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0006_rename_name_installer_username_installer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Jane', max_length=302),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='Doe', max_length=30),
        ),
    ]
