# Generated by Django 4.2.9 on 2024-02-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0008_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
