# Generated by Django 4.2.9 on 2024-02-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0009_alter_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='installer',
        ),
        migrations.AlterField(
            model_name='installer',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='installers', to='solarapp.userprofile'),
        ),
    ]
