# Generated by Django 4.2.9 on 2024-02-04 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0010_remove_userprofile_installer_alter_installer_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='installer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='solarapp.installer'),
        ),
    ]
