# Generated by Django 4.2.9 on 2024-02-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0011_remove_installer_users_userprofile_installer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='first_name',
            field=models.CharField(default='Jane', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='James', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='JOrbAzmpIN8ut2', max_length=100),
        ),
    ]
