# Generated by Django 4.2.9 on 2024-02-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0013_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$CNy0nmudBz0es4sus8WzOI$z6+7tDETExatWvNOGJDpsGPM1VXFWlrNjTbCcWcu9u0=', max_length=100),
        ),
    ]
