# Generated by Django 4.2.9 on 2024-02-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0014_alter_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='installer',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$37Kg7Rcp8LX1L1q8KyblOP$PzyizhVXfipzCC+DMu8KFHhM3SebLlqXQJ1uWxK7Wtc=', max_length=100),
        ),
    ]
