# Generated by Django 4.2.9 on 2024-02-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0015_remove_userprofile_installer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='installer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='solarapp.installer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$EYjjEZINsVmdJWPe0fYqKo$YBe3Y8roe6PPshhg2JPF1jbwWhZdK9hgFwCWYOPgmmw=', max_length=100),
        ),
    ]
