# Generated by Django 4.2.9 on 2024-02-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0016_userprofile_installer_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LpQ5JxfBbkR2tEgXWvBCdb$v4PIa6UDJiaHBi779kGgojJFzhYjieO8NobG7p+4KIM=', max_length=100),
        ),
    ]
