# Generated by Django 4.2.9 on 2024-02-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0017_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$557ZZHwbACoYIwcJ6WzMjU$rBq80AvpMNy2FXF1k1IbFiYoE+UN7dYPcB98z28fdoM=', max_length=100),
        ),
    ]
