# Generated by Django 4.2.9 on 2024-02-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0018_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$qBheWZnHNlSW5oLNezW2xv$JBMu8yHUo7pjx1ai4hmiCdIa0XEUxe1t0wsCZRDq6oQ=', max_length=100),
        ),
    ]
