# Generated by Django 4.2.9 on 2024-02-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0020_alter_installer_options_alter_installer_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$uc410vblI5vXkReWs5EzxV$lYh9dC13zMr1O3xMnp46zDSo/oC+m8P4RjIFNqdkqeA=', max_length=100),
        ),
    ]
