# Generated by Django 4.2.9 on 2024-02-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0021_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zIOd9icRI4BmfJ8HoS5g5C$5CFE3k1mxrKU7FWw5Pk+GOrijO+p+G4OZFjgDFdHYc8=', max_length=100),
        ),
    ]
