# Generated by Django 4.2.9 on 2024-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0022_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$gvSp4YykqbpklofqgFkhrH$XGSnuZuZnOmTGUyUJD9Ma80+qSwFwOawnqJXK9w6BfI=', max_length=100),
        ),
    ]
