# Generated by Django 4.2.9 on 2024-02-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0023_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LIPZw8X4tNqg0cGF2MER7I$x7y6oHbhsSL8WdY68C64kFwJ9MVXN03v+MUJZmgZNI0=', max_length=100),
        ),
    ]
