# Generated by Django 4.2.9 on 2024-02-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0024_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$wQxBjACHfeeMm22Ut9hghS$xdJNDMG/0ELKciKOtQPtk0jvqufma/Q1sz2qW44sMEQ=', max_length=100),
        ),
    ]
