# Generated by Django 4.2.9 on 2024-02-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0025_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$kVLVRQa6F03HZY7J5Ha9ft$4s69h1wxBxBjjFjhH0pn0a+eHtkGkn30iPtDHlR8PpU=', max_length=100),
        ),
    ]
