# Generated by Django 4.2.9 on 2024-02-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0026_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$g2HaHQdJ0Vu09LrBzeuJIo$YNQyULmgl6xb770XQZa7Q2Z2jlsDMiXbRG0F2+j06Rw=', max_length=100),
        ),
    ]
