# Generated by Django 4.2.9 on 2024-02-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0027_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$HcUc4T8foGutO21tIU6Bh9$t+Nr5JANjgND0o3lsCIOq2ETTi/7H3mOXugt4QfZea8=', max_length=100),
        ),
    ]
