# Generated by Django 4.2.9 on 2024-02-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0028_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Nphkqxo53Kay0FKyDxaYtZ$vKMYtIGsxi8wv7PiJJ8h1AJBDF6pc7HVyESdbvWqHu8=', max_length=100),
        ),
    ]
