# Generated by Django 4.2.9 on 2024-02-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0029_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$xsGPahHC27zmevOT88m0bW$NBKntomds5D8XLoRCg0WuBPJNERDkijtxB5tex2X5as=', max_length=100),
        ),
    ]
