# Generated by Django 4.2.9 on 2024-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0030_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='installer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='installer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='installer',
            name='email',
            field=models.EmailField(default='janeDoe@greek.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='installer',
            name='first_name',
            field=models.CharField(default='Jane', max_length=30),
        ),
        migrations.AlterField(
            model_name='installer',
            name='last_name',
            field=models.CharField(default='Doe', max_length=30),
        ),
        migrations.AlterField(
            model_name='installer',
            name='password',
            field=models.CharField(default='password123', max_length=100),
        ),
        migrations.AlterField(
            model_name='installer',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$8X6and3psdtCssXywaU4gA$cRq6fnbYzpe/PSnQ0zu7DR/jip8PrbcqDB7DEx99pFk=', max_length=100),
        ),
    ]
