# Generated by Django 4.2.9 on 2024-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0031_alter_installer_options_alter_installer_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$DDdC0eaZIQBNiGP2rtNQfP$6vnDb9gc9aOdty7soe5oeZhqS/Dh7vGBNJwfnE1CYGg=', max_length=100),
        ),
    ]
