# Generated by Django 4.2.9 on 2024-02-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0032_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$wyeYRAhBU4w5TIcFhpYn5b$YEJvhuR2bOXIt4rupd6GraMpSB45ZQ0pwJcPiWsPUzY=', max_length=100),
        ),
    ]
