# Generated by Django 4.2.9 on 2024-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0033_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$qQeBgFxGVxNtvrjkk33hSe$lEYpUedAoT4k309fVrd0X0Dq7lmmUkfoV0qHSJp7VrA=', max_length=100),
        ),
    ]
