# Generated by Django 4.2.9 on 2024-02-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0035_alter_installer_options_alter_installer_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Rhioirbcvm1mgcuEbjmFJp$BjxvIuGkGSm8HTDpBMx7EkAk2xEcD7Wocjt772ffADs=', max_length=100),
        ),
    ]
