# Generated by Django 4.2.9 on 2024-02-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0037_baseuser_remove_userprofile_installer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={},
        ),
    ]
