# Generated by Django 4.2.9 on 2024-02-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0038_alter_baseuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
