# Generated by Django 4.2.9 on 2024-02-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0039_alter_baseuser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Installer',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(default='jamesBrown@greek.com', max_length=254)),
            ],
        ),
    ]
