# Generated by Django 4.2.9 on 2024-02-06 21:03

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0040_delete_installer_delete_userprofile_installer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Installer',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.CreateModel(
            name='Installer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('solarapp.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('solarapp.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
